apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: build-demo
spec:
  workspaces:
  - name: shared-workspace
  params:
  - name: git-url
    type: string
    description: url of the git repo for the code of deployment
    default: https://github.com/jacobnelmark36/guide-openshift-local-crc.git
  - name: git-revision
    type: string
    description: revision to be used from repo of the code for deployment
    default: dev2
  - name: git-repo-name
    type: string
    description: git repo name
    default: system-app
  - name: file-path
    type: string
    description: path to Readme.md in repo
    default: workspace/repo/system/Readme.md
  - name: IMAGE
    type: string
    description: Fully qualified container image name to be built by Buildah.
    default: image-registry.openshift-image-registry.svc:5000/pipeline-demo/system:1.0-SNAPSHOT
  - name: DOCKERFILE
    type: string
    description: Path to the Dockerfile (or Containerfile) relative to the source workspace.
    default: workspace/source/system/Dockerfile
  - name: CONTEXT
    type: string
    description: Path to the directory to use as the context.
    default: workspace/source/system/
  tasks:
  - name: clone-repo
    taskRef:
      resolver: git
      params:
      - name: url
        value: https://github.com/jacobnelmark36/rhos-pipelines.git
      - name: revision
        value: main
      - name: pathInRepo
        value: ci/tasks/git-clone.yaml
    workspaces:
    - name: repo
      workspace: shared-workspace
    params:
    - name: url
      value: $(params.git-url)
    - name: subdirectory
      value: ""
    - name: deleteExisting
      value: "true"
    - name: revision
      value: $(params.git-revision)
  - name: echo-readme
    workspaces:
    - name: repo
      workspace: shared-workspace
    params:
    - name: repoName
      value: $(params.git-repo-name)
    - name: filePath
      value: $(params.file-path)
    runAfter:
    - clone-repo
    taskSpec:
      params:
      - name: repoName
        type: string
      - name: filePath
        type: string
      steps:
      - image: ubuntu
        script: |
          #!/bin/bash
          ls -la
          cat $(params.filePath)
          echo "name of repo: $(params.repoName)"
  - name: build-image
    taskRef:
      resolver: cluster
      params:
      - name: kind
        value: task
      - name: name
        value: buildah
      - name: namespace
        value: openshift-pipelines
    runAfter:
    - echo-readme
    params:
    - name: IMAGE
      value: $(params.IMAGE)
    - name: DOCKERFILE
      value: $(params.DOCKERFILE)
    - name: CONTEXT
      value: $(params.CONTEXT)
    workspaces:
    - name: source
      workspace: shared-workspace

