apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: build-demo-event-listener
spec:
  serviceAccountName: pipeline
  triggers:
  - name: build-demo-trigger
    bindings:
    - ref: build-demo-binding
    template:
      ref: build-demo-template